name: RecipeChatBot
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - cpuonly
  - portaudio
  - pyaudio
  - ffmpeg
  - git
  - jupyter
  - pip
  - pillow
  - pip:
      - gpt4all==2.8.2
      - SpeechRecognition
      - gTTS
      - pyttsx3
      - openai
      - python-dotenv
      - pydub
      - transformers
      - datasets
      - huggingface_hub==0.25.0
      - ttkthemes